name: App Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DATABASE_URL: "file:./test.db"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Lint Client (ESLint)
        run: cd client && bun run lint

      - name: Verify Environment Variables
        run: echo "JWT_SECRET=$JWT_SECRET" && echo "DATABASE_URL=$DATABASE_URL"

      - name: Run Tests
        run: |
          export JWT_SECRET=$JWT_SECRET
          export DATABASE_URL=$DATABASE_URL
          npx prisma db push --schema=./server/prisma/schema.prisma
          bun test

      - name: Build and Deploy Server
        run: |
          cd client && bun run build
          cd ../server && bun run start &
          sleep 10
          kill -SIGINT $(jobs -p) # Gracefully shut down the server
